# Generated by Django 4.2.5 on 2023-09-12 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokeleagueapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
    ]
