# Generated by Django 4.2.5 on 2023-09-13 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokeleagueapp', '0002_remove_event_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(default='pokemon league'),
            preserve_default=False,
        ),
    ]
